# To use:
#
#   $ mamba env create -f environment.yml  # `conda` works too for this command
#   $ mamba activate indar-dev
#
name: indar-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - attrs
  - pytest
  - numpy=2.4
  - scipy=1.17
  - scikit-learn=1.8
  - pandas
  - matplotlib
  - sympy
  - sphinx
  - numpydoc
  - pip
  - pip:
    - hatch
    - hatch-requirements-txt
    - jitcode
    - symengine
    - pip-tools
    - sphinx-nefertiti
