# To use:
#
#   $ mamba env create -f environment.yml  # `conda` works too for this command
#   $ mamba activate indar-dev
#
name: indar-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - attrs
  - pytest
  - numpy=2.4
  - scipy=1.17
  - scikit-learn=1.8
  - pandas=3.0
  - matplotlib=3.10
  - sympy=1.14
  - sphinx
  - numpydoc
  - pip
  - pip:
    - hatch
    - hatch-requirements-txt
    - jitcode==1.7
    - symengine==0.14
    - pip-tools
    - sphinx-nefertiti
    - sphinx-copybutton
