# To use:
#
#   $ mamba env create -f environment.yml  # `conda` works too for this command
#   $ mamba activate numpy-dev
#
name: indar-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.13
  - attrs
  - pytest
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - matplotlib
  - sympy
  - pip>=23.1
  - pip:
    - hatch
    - hatch-requirements-txt
    - jitcode
    - symengine
    - pip-tools
